---
title: "Google Analytics"
author: "Chris Beeley"
date: "22 April 2015"
output: html_document
runtime: shiny
---

Credits go to [here](http://rud.is/b/2014/12/29/making-static-interactive-maps-with-ggvis-using-ggvis-maps-wshiny/) and [here](http://stackoverflow.com/questions/22625119/choropleth-world-map)

# Session counts

```{r, echo=FALSE, message = FALSE}

######################################
########### Data section #############
######################################

library(RGoogleAnalytics)
library(dplyr)
library(ggplot2)
library(rgdal)
library(RColorBrewer)
library(ggvis)
library(shiny)

load("gadf.Rdata")

### top 3 domains

topThree = group_by(gadf, networkDomain) %>%
  summarise(counts = mean(users)) %>%
  arrange(desc(counts)) %>%
  slice(1:3) %>%
  select(networkDomain)

groupByDate = filter(gadf, networkDomain %in% topThree$networkDomain) %>%
  group_by(YearMonth, networkDomain) %>%
  summarise(meanSession = mean(sessionDuration, na.rm = TRUE), users = sum(users),
            newUsers = sum(newUsers), sessions = sum(sessions))

groupByDate$Date = as.Date(paste0(groupByDate$YearMonth, "01"), format = "%Y%m%d")

# note sessions are in seconds

inputPanel(
  checkboxInput("smooth", label = "Add smoother?", value = FALSE)
  )

renderPlot({
  
  thePlot = ggplot(groupByDate, aes(x = Date, y = meanSession, group = networkDomain, colour = networkDomain)) +
    geom_line() + ylim(0, max(groupByDate$meanSession))
  
  if(input$smooth){
    
    thePlot = thePlot + geom_smooth()
    }
  
  print(thePlot)
  
  })

```

# Country map

```{r, echo=FALSE, message=FALSE, warning=FALSE, results='hide'}

groupCountry = group_by(gadf, country)

groupByCountry = summarise(groupCountry, totalSeconds = sum(sessionDuration), users = sum(users),
                           newUsers = sum(newUsers), sessions = sum(sessions))

world = readOGR(dsn=".", layer="world_country_admin_boundary_shapefile_with_fips_codes")

countries = world@data

countries = cbind(id = rownames(countries), countries)

countries = merge(countries, groupByCountry, by.x = "CNTRY_NAME", by.y = "country", all.x = TRUE)

map.df = fortify(world)

map.df = merge(map.df, countries, by = "id")

ggplot(map.df, aes(x = long, y = lat, group = group)) +
  geom_polygon(aes(fill = log(users))) +
  geom_path(colour = "grey50") +
  scale_fill_gradientn(name = "log users",
                       colours = rev(brewer.pal(9, "Spectral")),
                       na.value = "white") +
  coord_fixed() + labs(x = "", y = "")

```

# Interactive country map

```{r, echo=FALSE}

getUsers = function(x){
  
  if(is.null(x)) return(NULL)
  
  theCountry = head(filter(map.df, id == x$id), 1)$CNTRY_NAME
  
  return(filter(groupByCountry, country == theCountry)$users)
  
  }

map.df %>%
  group_by(group, id) %>%
  ggvis(~long, ~lat) %>%
  layer_paths(fill = ~ users) %>%
  scale_numeric("fill", trans = "log", label = "log(users)") %>%
  add_tooltip(getUsers, "click")  %>%
  hide_axis("x") %>% hide_axis("y")

```
